version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: shubhamv-codes
      MONGO_INITDB_ROOT_PASSWORD: Shubham@123
      MONGO_INITDB_DATABASE: my-sample-db
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: shubhamv-codes
      ME_CONFIG_MONGODB_ADMINPASSWORD: Shubham@123
      ME_CONFIG_MONGODB_URL: mongodb://shubhamv-codes:Shubham%40123@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false

